### ISSUE TITLE
Whitespace in base64 encoding

### ISSUE THREAD

**Issue by skiedude** [Chipsoid/EveOnline-SSO#1]
I kept receiving a 401 when trying to do the get_token(), finally after some debugging I found that base64_encode was adding whitespace to my base64 encoded string that was being passed in as the authorization. Upon researching the issue, its a "known" bug with this function and the way around it is to pass an "" after the value. 

Passing it inside the default_header call didn't seem to work, LWP complained about it so I moved it out to one line above. 

`    my $base64 = encode_base64($self->client_id.':'.$self->client_secret, "");
    $self->ua->default_header('Authorization' => "Basic " . $base64);`
http://www.perlmonks.org/?node_id=660422

**Comment by Chipsoid** [comment]
Thanks. Fixed
